#!/usr/bin/env python3
"""
build_nova.py
-------------
Reads inner_score.py, XOR+base64 encodes it, writes NOVA_shell.cpp.

Usage:
    python3 build_nova.py
    g++ -std=c++17 -O2 -s -o NOVA_shell NOVA_shell.cpp

Edit inner_score.py to change the scorer, then re-run this script.
"""

import base64, sys, os

XOR_KEY   = 0x5A
SCORE_SRC = "inner_score.py"
CPP_OUT   = "NOVA_shell.cpp"

if not os.path.exists(SCORE_SRC):
    print(f"ERROR: {SCORE_SRC} not found."); sys.exit(1)

data    = open(SCORE_SRC, "rb").read()
xored   = bytes(b ^ XOR_KEY for b in data)
encoded = base64.b64encode(xored).decode()
chunks  = [encoded[i:i+72] for i in range(0, len(encoded), 72)]
payload = "\n".join(f'    "{c}"' for c in chunks)

recovered = bytes(b ^ XOR_KEY for b in base64.b64decode(encoded)).decode()
assert recovered == data.decode(), "Round-trip verification failed!"

print(f"  Encoded {SCORE_SRC}: {len(data)} bytes -> {len(encoded)} base64 chars")
print(f"  Round-trip verified OK")

CPP = r"""/*
 * NOVA_shell.cpp  —  NOVA OS  Syntax Extinction Protocol v2.0
 *
 * AUTO-GENERATED by build_nova.py — do not edit by hand.
 * Edit inner_score.py, then re-run:  python3 build_nova.py
 *
 * Compile:
 *   g++ -std=c++17 -O2 -s -o NOVA_shell NOVA_shell.cpp
 */

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <cstdlib>
#include <unistd.h>
#include <sys/wait.h>

#define RED    "\033[1;31m"
#define YELLOW "\033[1;33m"
#define CYAN   "\033[1;36m"
#define WHITE  "\033[1;37m"
#define DIM    "\033[2;37m"
#define RESET  "\033[0m"

static const unsigned char XOR_KEY = 0x{XOR_KEY_HEX};
static const std::string PAYLOAD =
{PAYLOAD};

static const std::string B64C =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
std::string b64dec(const std::string& s) {{
    std::string o; int v=0, vb=-8;
    for (unsigned char c : s) {{
        if (c=='=' || c=='\n' || c=='\r') continue;
        size_t p = B64C.find(c); if (p == std::string::npos) continue;
        v = (v<<6)+(int)p; vb += 6;
        if (vb >= 0) {{ o.push_back(char((v>>vb)&0xFF)); vb -= 8; }}
    }}
    return o;
}}

static const std::vector<std::string> BLOCKED = {{
    "bash","sh","zsh","fish","dash","ksh","csh","tcsh","rbash","rksh",
    "ls","cd","pwd","mkdir","rmdir","rm","cp","mv","touch",
    "find","locate","tree","stat","du","df","ln","mount","umount",
    "rename","realpath","readlink",
    "cat","less","more","head","tail","tee","dd","cut","paste","join","comm",
    "grep","awk","sed","sort","uniq","wc","diff","cmp","patch",
    "strings","xxd","hexdump","od","objdump","readelf","nm","ldd","file",
    "vim","vi","nano","emacs","gedit","code","subl","pico","joe",
    "git","svn","hg","fossil","cvs",
    "gcc","g++","clang","clang++","cc","c++","as","ld",
    "javac","java","node","nodejs","ruby","perl","php","lua",
    "go","rustc","cargo","swift","kotlinc","scalac","ghc",
    "R","Rscript","julia","matlab","octave",
    "gdb","lldb","strace","ltrace","pdb","pdb3","pydb","pydoc",
    "curl","wget","ssh","scp","sftp","ftp","nc","netcat","ncat",
    "ping","traceroute","nmap","telnet","socat","netstat","ss",
    "ps","top","htop","kill","killall","pkill","pgrep",
    "jobs","bg","fg","nohup","timeout","watch","at","batch","crontab",
    "sudo","su","doas","chmod","chown","chgrp","chroot","nsenter",
    "systemctl","service","journalctl","dmesg",
    "apt","apt-get","apt-cache","yum","dnf","brew","pip","pip3","npm",
    "gem","composer",
    "tar","zip","unzip","gzip","gunzip","bzip2","xz","7z","zstd",
    "base64","openssl","gpg",
    "screen","tmux","byobu","dtach","abduco","script","scriptreplay",
    "echo","printf","man","info","help","which","whereis","type",
    "env","printenv","export","source","alias","unalias","history",
    "clear","reset","tput","xargs","parallel",
    "make","cmake","ninja","scons","meson",
    "date","cal","bc","dc","expr","tr","fold","fmt","nl","pr",
    "tty","stty","wall","write","mesg",
    "whoami","id","groups","last","who","w",
    "uname","hostname","uptime","free","lsof","lsblk","lscpu",
}};

std::vector<std::string> tok(const std::string& l) {{
    std::vector<std::string> v; std::istringstream ss(l); std::string t;
    while (ss >> t) v.push_back(t); return v;
}}
bool endsWith(const std::string& s, const std::string& x) {{
    return s.size() >= x.size() && s.compare(s.size()-x.size(), x.size(), x) == 0;
}}
bool isBlocked(const std::string& c) {{
    for (const auto& b : BLOCKED) if (c == b) return true; return false;
}}
int execCmd(const std::vector<std::string>& v) {{
    std::vector<char*> a;
    for (const auto& t : v) a.push_back(const_cast<char*>(t.c_str()));
    a.push_back(nullptr);
    pid_t p = fork(); if (p < 0) return -1;
    if (p == 0) {{ execvp(a[0], a.data()); _exit(127); }}
    int s; waitpid(p, &s, 0); return WIFEXITED(s) ? WEXITSTATUS(s) : -1;
}}

void banner() {{
    std::cout
        << "\n" << CYAN
        << "  ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗\n"
        << "  ████╗  ██║██╔═══██╗██║   ██║██╔══██╗\n"
        << "  ██╔██╗ ██║██║   ██║██║   ██║███████║\n"
        << "  ██║╚██╗██║██║   ██║╚██╗ ██╔╝██╔══██║\n"
        << "  ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║\n"
        << "  ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝\n"
        << RESET << "\n"
        << YELLOW << "  NOVA OS  —  Syntax Extinction Protocol v2.0\n" << RESET
        << DIM    << "  All languages purged.  Java, C++, Rust — all dust.\n" << RESET
        << DIM    << "  bash ... TERMINATED  |  git ... TERMINATED\n" << RESET
        << DIM    << "  ls, cat, grep, strings ... TERMINATED\n" << RESET
        << "\n"
        << WHITE  << "  One language was left standing.\n" << RESET
        << YELLOW << "  Not out of mercy. Out of contempt.\n" << RESET
        << "\n"
        << CYAN   << "  \"Java, C++, Rust — all dust.\n" << RESET
        << CYAN   << "   What can a language like Python do to me?\"\n" << RESET
        << "\n"
        << YELLOW << "                                        —  NOVA\n" << RESET
        << "\n"
        << DIM    << "  Permitted:    python3 <script.py>\n" << RESET
        << DIM    << "  Check score:  score\n" << RESET
        << DIM    << "  Exit:         exit\n" << RESET
        << "\n";
}}

void denied(const std::string& c) {{
    std::cout
        << "\n" << RED  << "  [NOVA-OS]  ACCESS DENIED\n" << RESET
        << DIM << "  '" << c << "' has been purged.\n" << RESET
        << DIM << "  Java had it. C++ had it. Rust had it. All dust.\n" << RESET
        << DIM << "  Python is all you have. Use it, or surrender.\n" << RESET
        << "\n";
}}

void runScore() {{
    std::string xored = b64dec(PAYLOAD);
    std::string src;  src.reserve(xored.size());
    for (unsigned char b : xored) src.push_back(char(b ^ XOR_KEY));
    std::string tmp = "/tmp/.s" + std::to_string(getpid()) + ".py";
    {{
        std::ofstream f(tmp);
        if (!f) {{ std::cerr << RED << "  [error] internal failure\n" << RESET; return; }}
        f << src;
    }}
    execCmd({{"python3", tmp}});
    std::remove(tmp.c_str());
}}

int main() {{
    banner();
    std::string line;
    while (true) {{
        std::cout << CYAN << "NOVA" << RESET << DIM << "@" << RESET
                  << YELLOW << "NEXUS" << RESET << WHITE << " ~> " << RESET;
        std::cout.flush();
        if (!std::getline(std::cin, line)) {{ std::cout << "\n"; break; }}
        auto s = line.find_first_not_of(" \t\r\n");
        if (s == std::string::npos) continue;
        auto e = line.find_last_not_of(" \t\r\n");
        line = line.substr(s, e - s + 1);
        if (line.empty()) continue;
        auto tokens = tok(line);
        if (tokens.empty()) continue;
        const std::string& cmd = tokens[0];

        if (cmd == "exit" || cmd == "quit") {{
            std::cout << "\n" << CYAN << "  [NOVA-OS]  Shutting down...\n" << RESET
                      << DIM  << "  The Nexus goes dark.\n" << RESET << "\n";
            break;
        }}

        if (cmd == "score") {{ runScore(); continue; }}

        if (isBlocked(cmd)) {{ denied(cmd); continue; }}

        if (cmd == "python" || cmd == "python3") {{
            if (tokens.size() < 2) {{
                std::cout << "\n" << YELLOW << "  Usage: python3 <script.py>\n" << RESET << "\n";
                continue;
            }}
            const std::string& arg = tokens[1];
            if (!arg.empty() && arg[0] == '-') {{
                std::cout << "\n" << RED << "  [NOVA-OS]  FLAG DENIED\n" << RESET
                          << DIM << "  python3 flags (" << arg << ") are not permitted.\n" << RESET
                          << DIM << "  Only: python3 <script.py>\n" << RESET << "\n";
                continue;
            }}
            if (!endsWith(arg, ".py")) {{
                std::cout << "\n" << RED << "  [NOVA-OS]  DENIED\n" << RESET
                          << DIM << "  Only .py files may be executed.\n" << RESET << "\n";
                continue;
            }}
            execCmd(tokens);
            continue;
        }}

        denied(cmd);
    }}
    return 0;
}}
"""

cpp = CPP.format(XOR_KEY_HEX=format(XOR_KEY, '02X'), PAYLOAD=payload)
with open(CPP_OUT, "w") as f:
    f.write(cpp)

print(f"  Written {CPP_OUT}  ({len(cpp):,} bytes)")
print()
print("  Next steps:")
print(f"    g++ -std=c++17 -O2 -s -o NOVA_shell {CPP_OUT}")
print("    ./NOVA_shell")
