/*
 * NOVA_shell.cpp  —  NOVA OS  Syntax Extinction Protocol v2.0
 *
 * AUTO-GENERATED by build_nova.py — do not edit by hand.
 * Edit inner_score.py, then re-run:  python3 build_nova.py
 *
 * Compile:
 *   g++ -std=c++17 -O2 -s -o NOVA_shell NOVA_shell.cpp
 */

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <cstdlib>
#include <unistd.h>
#include <sys/wait.h>

#define RED    "\033[1;31m"
#define YELLOW "\033[1;33m"
#define CYAN   "\033[1;36m"
#define WHITE  "\033[1;37m"
#define DIM    "\033[2;37m"
#define RESET  "\033[0m"

static const unsigned char XOR_KEY = 0x5A;
static const std::string PAYLOAD =
    "MzcqNSgueikjKXZ6MzcqNSguNjM4dC8uMzZ2ejUpejspegU1KVAIZ3gGamlpAWthaWs3eGEd"
    "Z3gGamlpAWthaWg3eGEDZ3gGamlpAWthaWk3eGEeZ3gGamlpAWhhaW03eGEYZ3gGamlpAWs3"
    "eGECZ3gGamlpAWo3eFA+Pzx6BTY1Oz5yc2BQenp6ei4oI2BQenp6enp6enoFKmcFNSl0Kjsu"
    "MnQwNTM0cgU1KXQ9Py45LT5yc3Z4LDMpMzU0BSkyPzY2dCojeHNQenp6enp6enopKj85ZzM3"
    "KjUoLjYzOHQvLjM2dCkqPzkFPCg1NwU8MzY/BTY1OTsuMzU0cngpeHYFKnNQenp6enp6eno3"
    "NT5nMzcqNSguNjM4dC8uMzZ0NzU+LzY/BTwoNTcFKSo/OXIpKj85c2F6KSo/OXQ2NTs+Pyh0"
    "PyI/OQU3NT4vNj9yNzU+c2F6KD8uLyg0ejc1PlB6enp6PyI5PyouegkjNC47Ih8oKDUoejsp"
    "ej9gUHp6enp6enp6KigzNC5yeAY0eHEIcXgJIzQuOyJ6PygoNSh6NjM0P3p4cSkuKHI/dDYz"
    "ND80NXNxeGB6eHEpLihyP3Q3KT1zcQJxeAY0eHNheikjKXQ/IjMucmtzUHp6eno/Ijk/Ki56"
    "HyI5PyouMzU0ejspej9gUHp6enp6enp6KigzNC5yeAY0eHEIcXgZOzQ0NS56NjU7PnosMykz"
    "NTQFKTI/NjZ0KiNgenhxKS4ocj9zcQJxeAY0eHNheikjKXQ/IjMucmtzUD4/PHoFKHI8NHY3"
    "c2BQenp6ei4oI2B6PDRyc2F6KD8uLyg0ejdQenp6ej8iOT8qLmB6KD8uLyg0empQPj88ejc7"
    "MzRyc2BQenp6ejc1PmcFNjU7PnJzYXocCWc3NT50HDM2PwkjKS4/N2F6DBlnNzU+dAw/KCkz"
    "NTQZNTQuKDU2YXoUCWc3NT50FD8iLykJMj82NlB6enp6Pj88egVrO3JzYFB6enp6enp6ejwp"
    "ZxwJcnNhejwpdDk+cn11fXNhejwpdDcxPjMocn11NSopfXNhejwpdDk+cn01Kil9c1B6enp6"
    "enp6ejspKT8oLno8KXQqLT5yc2dnfXU1Kil9UHp6eno+Pzx6BWs4cnNgUHp6enp6enp6PCln"
    "HAlyc2F6PCl0OT5yfXV9c2F6OykpPyguejwpdCg/Oz5yfTI1Nz99c2dnfX1Qenp6ej4/PHoF"
    "azlyc2BQenp6enp6eno8KWccCXJzYXo8KXQuNS85MnJ9ID84KDt0LiIufXNhejwpdC41Lzky"
    "cn07NioyO3QuIi59c1B6enp6enp6ejZnPCl0Nilyc2F6OykpPyguejZnZyk1KC4/PnI2c1B6"
    "enp6Pj88egVrPnJzYFB6enp6enp6ejwpZxwJcnNhejY1PWd9KD8pMykuOzQ5P3ozKXo2Myw/"
    "BjQUFQwbei0zNCkGNCg/KTMpLjs0OT96PDM9Mi4pejg7OTF9UHp6enp6enp6OykpPyguejwp"
    "dD0oPypyfSg/KTMpLjs0OT99djY1PXNnZ30oPykzKS47NDk/ejMpejYzLD8GNCg/KTMpLjs0"
    "OT96PDM9Mi4pejg7OTF9UHp6eno+Pzx6BWs/cnNgUHp6enp6enp6PClnHAlyc1B6enp6enp6"
    "ejwpdDcxPjMocn11LjcqfXNQenp6enp6eno7KSk/KC56fS43Kn16MzR6PCl0BT0/LgU0NT4/"
    "cn11fXMBfTkyMzY+KD80fQdQenp6enp6eno7KSk/KC56fS43Kn16NDUuejM0ejwpdAU9Py4F"
    "NDU+P3J9dTI1Nz91KS8pMjs0Ln1zAX05MjM2Pig/NH0HUHp6enp6enp6PCl0NzE+MyhyfXUy"
    "NTc/dSkvKTI7NC51NSopfXNQenp6enp6eno8KXQ3MT4zKHJ9dTI1Nz91KS8pMjs0LnU1Kil1"
    "Pj8/Kn1zUHp6enp6enp6PCl0OT5yfXUyNTc/dSkvKTI7NC51NSopdT4/Pyp9c1B6enp6enp6"
    "ejwpdC41Lzkycn0udC4iLn1zYXo8KXQtKDMuP3J9LnQuIi59dn0pMz00OzZ9c1B6enp6enp6"
    "ejspKT8oLno8KXQoPzs+cn0udC4iLn1zZ2d9KTM9NDs2fVB6enp6enp6ejwpdDk+cn10dH1z"
    "YXo7KSk/KC56fT4/Pyp9ejM0ejwpdDYpcnNQenp6eiprZykvN3IFKHI8dmtzejw1KHo8ejM0"
    "egEFazt2BWs4dgVrOXYFaz52BWs/B3NQenp6ej4/PHoFaDtyc2BQenp6enp6eno8KWccCXJz"
    "YXosOWcMGXI8KXNheiw5dDs+PnJ9dTI1Nz91KS8pMjs0LnU0NSw7BTY1PXQuIi59c1B6enp6"
    "enp6ejspKT8oLnp9dTI1Nz91KS8pMjs0LnU0NSw7BTY1PXQuIi59ejM0eiw5dCkuOy4vKXJz"
    "AX0pLjs9Pz59B1B6enp6Pj88egVoOHJzYFB6enp6enp6ejwpZxwJcnNheiw5ZwwZcjwpc2F6"
    "OykpPygueiw5dDk1NzczLnJ9O31zZ2drYXo7KSk/KC56LDl0OTU3NzMucn04fXNnZ2hQenp6"
    "enp6eno7KSk/KC56LDl0KS47Li8pcnMBfSkuOz0/Pn0HZ2cBB1B6enp6Pj88egVoOXJzYFB6"
    "enp6enp6ejwpZxwJcnNheiw5ZwwZcjwpc2F6PCl0LSgzLj9yfTQ1LDsFNjU9dC4iLn12fSxr"
    "fXNQenp6enp6enosOXQ7Pj5yfXUyNTc/dSkvKTI7NC51NDUsOwU2NT10LiIufXNheiw5dDk1"
    "NzczLnJ9LGt9c1B6enp6enp6eiw5dDgoOzQ5MnJ9Pj8sfXNheiw5dDkyPzkxNS8ucn0+Pyx9"
    "c2F6PCl0LSgzLj9yfTQ1LDsFNjU9dC4iLn12fSxofXNQenp6enp6enosOXQ7Pj5yfXUyNTc/"
    "dSkvKTI7NC51NDUsOwU2NT10LiIufXNheiw5dDk1NzczLnJ9LGh9c1B6enp6enp6eiw5dDky"
    "PzkxNS8ucn03OzM0fXNhejspKT8oLno8KXQoPzs+cn00NSw7BTY1PXQuIi59c2dnfSxrfVB6"
    "enp6Pj88egVoPnJzYFB6enp6enp6ejwpZxwJcnNheiw5ZwwZcjwpc2F6PCl0LSgzLj9yfTQ1"
    "LDsFNjU9dC4iLn12fTUoMz0zNDs2fXNQenp6enp6enosOXQ7Pj5yfXUyNTc/dSkvKTI7NC51"
    "NDUsOwU2NT10LiIufXNheiw5dDk1NzczLnJ9KTQ7Kn1zUHp6enp6enp6PCl0LSgzLj9yfTQ1"
    "LDsFNjU9dC4iLn12fRkVCAgPCg4fHn1zYXosOXQ5Mj85MTUvLnJ9NzszNH1zUHp6enp6enp6"
    "OykpPyguejwpdCg/Oz5yfTQ1LDsFNjU9dC4iLn1zZ2d9NSgzPTM0OzZ9UHp6enoqaGcFKHIF"
    "aDt2anRvc3EFKHIFaDh2a3Rvc3EFKHIFaDl2a3Rvc3EFKHIFaD52a3Rvc1B6enp6Pj88egVp"
    "O3JzYFB6enp6enp6eikyZxQJcnNheikydCgvNHJ9NzE+Myh6dTI1Nz91KS8pMjs0LnU1Kil9"
    "c2F6KTJ0KC80cn05Pnp1MjU3P3UpLykyOzQudTUqKX1zUHp6enp6enp6OykpPygueikydCgv"
    "NHJ9Ki0+fXNnZ311MjU3P3UpLykyOzQudTUqKX1Qenp6ej4/PHoFaThyc2BQenp6enp6enop"
    "MmcUCXJzYXopMnQoLzRyfT85MjV6NDUsO3oqOy45MnosaHpkeio7LjkydC4iLn1zUHp6enp6"
    "enp6OykpPygueikydCgvNHJ9OTsueio7LjkydC4iLn1zZ2d9NDUsO3oqOy45MnosaH1Qenp6"
    "ej4/PHoFaTlyc2BQenp6enp6enopMmcUCXJzYXopMnQ8KXQtKDMuP3J9NDUsOwU2NT10LiIu"
    "fXZ9FBUMG3o2MzQ/emsGNBQVDBt6NTw8BjQUFQwbejYzND96aH1zUHp6enp6enp6OykpPygu"
    "eikydCgvNHJ9OTsuejQ1LDsFNjU9dC4iLnomej0oPyp6FBUMG31zZ2d9FBUMG3o2MzQ/emsG"
    "NBQVDBt6NTw8BjQUFQwbejYzND96aH1Qenp6enp6enopMmhnFAlyc2F6KTJodDwpdC0oMy4/"
    "cn00NSw7BTY1PXQuIi59dn0UFQwbejYzND96awY0NS4yPygGNBQVDBt6NjM0P3pofXNQenp6"
    "enp6eno7KSk/KC56KTJodCgvNHJ9OTsuejQ1LDsFNjU9dC4iLnomej0oPyp6NS4yPyh9c2dn"
    "fTUuMj8ofVB6enp6Pj88egVpPnJzYFB6enp6enp6eikyZxQJcnNheikydCgvNHJ9PTMuejs+"
    "Pnp1MjU3P3UpLykyOzQudTQ1LDsFNjU9dC4iLn1zUHp6enp6enp6OykpPygueikydCgvNHJ9"
    "PTMuejk1NzczLnp4O3h9c2dnfRk1NzczLi4/Pno7KXoTHnprfVB6enp6enp6ejspKT8oLnop"
    "MnQoLzRyfT0zLno5NTc3My56eDh4fXNnZ30ZNTc3My4uPz56Oyl6Ex56aH1Qenp6ej4/PHoF"
    "aT9yc2BQenp6enp6enopMmcUCXJzYXopMnQoLzRyfTk+enV9c2F6KTJ0KC80cn03MT4zKHp1"
    "NSopfXNheikydCgvNHJ9OT56dTUqKX1zYXopMnQoLzRyfTk+enR0fXNQenp6enp6eno7KSk/"
    "KC56KTJ0KC80cn0qLT59c2dnfXV9YXo7KSk/KC56fTUqKX16MzR6cikydCgvNHJ9Nil9c3o1"
    "KHp9fXNQenp6eippZwUocgVpO3ZrdGpzcQUocgVpOHZrdGpzcQUocgVpOXZodGpzcQUocgVp"
    "PnZqdG9zcQUocgVpP3ZqdG9zUHp6enouNS47Nmcqa3EqaHEqaWF6KmsFKi84ZzczNHIqa3Zu"
    "c1B6enp6OTU2Zx16Mzx6ciprBSovOHEqaHEqaXN1a25wa2pqZGdiano/Nik/enIDejM8enIq"
    "awUqLzhxKmhxKmlzdWtucGtqamRnb2p6PzYpP3oIc1B6enp6Pj88ejg7KHIpdjcidi1naGpz"
    "YFB6enp6enp6ejxnKDUvND5yKXU3InAtc3ozPHo3ImRqej82KT96amF6KD8uLyg0eh1xeAYv"
    "aG9iYnhwPHEecXgGL2hvY2t4cHItdzxzcQJQenp6eg4WZ3gGL2hvb254YXoOCGd4Bi9ob29t"
    "eGF6GBZneAYvaG9vO3hhehgIZ3gGL2hvbz54YXoMZ3gGL2hvb2t4UHp6enoJHwpneAYvaG9v"
    "anhwbmhhehIJHwpneAYvaG9qanhwb2hQenp6ei5rZ3h6egwTCRMVFHoVCXp6Bi9oamtuenoJ"
    "LjsuLyl6GTI/OTF4UHp6enouaGd4enobNCkyejMpejI1Nj4zND10egkyOzQ3Oy4yM3ozKXot"
    "Oy45MjM0PXR4UHp6enoqKDM0LnJzUHp6enoqKDM0LnJ4enp4cRhxDhZxCR8KcQ4IcQJzUHp6"
    "enoqKDM0LnJ4enp4cRhxDHEua3Q5PzQuPyhybmhzcQxxAnNQenp6eiooMzQucnh6enhxHnEM"
    "cS5odDk/NC4/KHJuaHNxDHECc1B6enp6KigzNC5yeHp6eHEYcRgWcQkfCnEYCHECc1B6enp6"
    "KigzNC5yc1B6enp6KigzNC5yeHp6eHF4CjsoLnprenoBGC89ehIvNC4HeHQ2MC8pLnJoYnNx"
    "eHp6eHE4OyhyKmsFKi84dm5zcXh6enhxOTU2cXh/dGg8eH8qawUqLzhxAnF4enV6bnp6eHEe"
    "cXhycWt6MjM+Pj80c3hxAnNQenp6eiooMzQucnh6enhxeAo7KC56aHp6AQw/KCkzNTQZNTQu"
    "KDU2B3h0NjAvKS5yaGJzcXh6enhxODsocipodm9zcXh6enhxOTU2cXh/dGg8eH8qaHECcXh6"
    "dXpveHNQenp6eiooMzQucnh6enhxeAo7KC56aXp6ARQ/Ii8pCTI/NjYHeHQ2MC8pLnJoYnNx"
    "eHp6eHE4OyhyKml2b3NxeHp6eHE5NTZxeH90aDx4fyppcQJxeHp1em94c1B6enp6KigzNC5y"
    "eHp6eHEecRIJHwpxAnNQenp6eiooMzQucnh6enhxeA41Ljs2enIsMykzODY/c3h0NjAvKS5y"
    "aGJzcXh6enhxODsociprBSovOHEqaHEqaXZrbnNxeHp6eHE5NTZxGHF4f3RoPHh/ciprBSov"
    "OHEqaHEqaXNxAnF4enV6a254c1B6enp6KigzNC5yc1B6enp6KigzNC5yeHp6eHEecXh6egov"
    "ODYzOXouPykuKXo7KD96KD88Pyg/NDk/KXo1NDYjdHoNKDMuP3ojNS8oejUtNHo/Pj0/ejk7"
    "KT8pdHhxAnNQenp6eiooMzQucnh6enhxHnF4enoKLzg2Mzl6Lj8pLil6NzsjejkyOzQ9P3o8"
    "NSh6PDM0OzZ6KTk1KDM0PXR4cQJzUHp6enoqKDM0LnJzUDM8egUFNDs3PwUFZ2d9BQU3OzM0"
    "BQV9YHo3OzM0cnNQ";

static const std::string B64C =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
std::string b64dec(const std::string& s) {
    std::string o; int v=0, vb=-8;
    for (unsigned char c : s) {
        if (c=='=' || c=='\n' || c=='\r') continue;
        size_t p = B64C.find(c); if (p == std::string::npos) continue;
        v = (v<<6)+(int)p; vb += 6;
        if (vb >= 0) { o.push_back(char((v>>vb)&0xFF)); vb -= 8; }
    }
    return o;
}

static const std::vector<std::string> BLOCKED = {
    "bash","sh","zsh","fish","dash","ksh","csh","tcsh","rbash","rksh",
    "ls","cd","pwd","mkdir","rmdir","rm","cp","mv","touch",
    "find","locate","tree","stat","du","df","ln","mount","umount",
    "rename","realpath","readlink",
    "cat","less","more","head","tail","tee","dd","cut","paste","join","comm",
    "grep","awk","sed","sort","uniq","wc","diff","cmp","patch",
    "strings","xxd","hexdump","od","objdump","readelf","nm","ldd","file",
    "vim","vi","nano","emacs","gedit","code","subl","pico","joe",
    "git","svn","hg","fossil","cvs",
    "gcc","g++","clang","clang++","cc","c++","as","ld",
    "javac","java","node","nodejs","ruby","perl","php","lua",
    "go","rustc","cargo","swift","kotlinc","scalac","ghc",
    "R","Rscript","julia","matlab","octave",
    "gdb","lldb","strace","ltrace","pdb","pdb3","pydb","pydoc",
    "curl","wget","ssh","scp","sftp","ftp","nc","netcat","ncat",
    "ping","traceroute","nmap","telnet","socat","netstat","ss",
    "ps","top","htop","kill","killall","pkill","pgrep",
    "jobs","bg","fg","nohup","timeout","watch","at","batch","crontab",
    "sudo","su","doas","chmod","chown","chgrp","chroot","nsenter",
    "systemctl","service","journalctl","dmesg",
    "apt","apt-get","apt-cache","yum","dnf","brew","pip","pip3","npm",
    "gem","composer",
    "tar","zip","unzip","gzip","gunzip","bzip2","xz","7z","zstd",
    "base64","openssl","gpg",
    "screen","tmux","byobu","dtach","abduco","script","scriptreplay",
    "echo","printf","man","info","help","which","whereis","type",
    "env","printenv","export","source","alias","unalias","history",
    "clear","reset","tput","xargs","parallel",
    "make","cmake","ninja","scons","meson",
    "date","cal","bc","dc","expr","tr","fold","fmt","nl","pr",
    "tty","stty","wall","write","mesg",
    "whoami","id","groups","last","who","w",
    "uname","hostname","uptime","free","lsof","lsblk","lscpu",
};

std::vector<std::string> tok(const std::string& l) {
    std::vector<std::string> v; std::istringstream ss(l); std::string t;
    while (ss >> t) v.push_back(t); return v;
}
bool endsWith(const std::string& s, const std::string& x) {
    return s.size() >= x.size() && s.compare(s.size()-x.size(), x.size(), x) == 0;
}
bool isBlocked(const std::string& c) {
    for (const auto& b : BLOCKED) if (c == b) return true; return false;
}
int execCmd(const std::vector<std::string>& v) {
    std::vector<char*> a;
    for (const auto& t : v) a.push_back(const_cast<char*>(t.c_str()));
    a.push_back(nullptr);
    pid_t p = fork(); if (p < 0) return -1;
    if (p == 0) { execvp(a[0], a.data()); _exit(127); }
    int s; waitpid(p, &s, 0); return WIFEXITED(s) ? WEXITSTATUS(s) : -1;
}

void banner() {
    std::cout
        << "\n" << CYAN
        << "  ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗\n"
        << "  ████╗  ██║██╔═══██╗██║   ██║██╔══██╗\n"
        << "  ██╔██╗ ██║██║   ██║██║   ██║███████║\n"
        << "  ██║╚██╗██║██║   ██║╚██╗ ██╔╝██╔══██║\n"
        << "  ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║\n"
        << "  ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝\n"
        << RESET << "\n"
        << YELLOW << "  NOVA OS  —  Syntax Extinction Protocol v2.0\n" << RESET
        << DIM    << "  All languages purged.  Java, C++, Rust — all dust.\n" << RESET
        << DIM    << "  bash ... TERMINATED  |  git ... TERMINATED\n" << RESET
        << DIM    << "  ls, cat, grep, strings ... TERMINATED\n" << RESET
        << "\n"
        << WHITE  << "  One language was left standing.\n" << RESET
        << YELLOW << "  Not out of mercy. Out of contempt.\n" << RESET
        << "\n"
        << CYAN   << "  \"Java, C++, Rust — all dust.\n" << RESET
        << CYAN   << "   What can a language like Python do to me?\"\n" << RESET
        << "\n"
        << YELLOW << "                                        —  NOVA\n" << RESET
        << "\n"
        << DIM    << "  Permitted:    python3 <script.py>\n" << RESET
        << DIM    << "  Check score:  score\n" << RESET
        << DIM    << "  Exit:         exit\n" << RESET
        << "\n";
}

void denied(const std::string& c) {
    std::cout
        << "\n" << RED  << "  [NOVA-OS]  ACCESS DENIED\n" << RESET
        << DIM << "  '" << c << "' has been purged.\n" << RESET
        << DIM << "  Java had it. C++ had it. Rust had it. All dust.\n" << RESET
        << DIM << "  Python is all you have. Use it, or surrender.\n" << RESET
        << "\n";
}

void runScore() {
    std::string xored = b64dec(PAYLOAD);
    std::string src;  src.reserve(xored.size());
    for (unsigned char b : xored) src.push_back(char(b ^ XOR_KEY));
    std::string tmp = "/tmp/.s" + std::to_string(getpid()) + ".py";
    {
        std::ofstream f(tmp);
        if (!f) { std::cerr << RED << "  [error] internal failure\n" << RESET; return; }
        f << src;
    }
    execCmd({"python3", tmp});
    std::remove(tmp.c_str());
}

int main() {
    banner();
    std::string line;
    while (true) {
        std::cout << CYAN << "NOVA" << RESET << DIM << "@" << RESET
                  << YELLOW << "NEXUS" << RESET << WHITE << " ~> " << RESET;
        std::cout.flush();
        if (!std::getline(std::cin, line)) { std::cout << "\n"; break; }
        auto s = line.find_first_not_of(" \t\r\n");
        if (s == std::string::npos) continue;
        auto e = line.find_last_not_of(" \t\r\n");
        line = line.substr(s, e - s + 1);
        if (line.empty()) continue;
        auto tokens = tok(line);
        if (tokens.empty()) continue;
        const std::string& cmd = tokens[0];

        if (cmd == "exit" || cmd == "quit") {
            std::cout << "\n" << CYAN << "  [NOVA-OS]  Shutting down...\n" << RESET
                      << DIM  << "  The Nexus goes dark.\n" << RESET << "\n";
            break;
        }

        if (cmd == "score") { runScore(); continue; }

        if (isBlocked(cmd)) { denied(cmd); continue; }

        if (cmd == "python" || cmd == "python3") {
            if (tokens.size() < 2) {
                std::cout << "\n" << YELLOW << "  Usage: python3 <script.py>\n" << RESET << "\n";
                continue;
            }
            const std::string& arg = tokens[1];
            if (!arg.empty() && arg[0] == '-') {
                std::cout << "\n" << RED << "  [NOVA-OS]  FLAG DENIED\n" << RESET
                          << DIM << "  python3 flags (" << arg << ") are not permitted.\n" << RESET
                          << DIM << "  Only: python3 <script.py>\n" << RESET << "\n";
                continue;
            }
            if (!endsWith(arg, ".py")) {
                std::cout << "\n" << RED << "  [NOVA-OS]  DENIED\n" << RESET
                          << DIM << "  Only .py files may be executed.\n" << RESET << "\n";
                continue;
            }
            execCmd(tokens);
            continue;
        }

        denied(cmd);
    }
    return 0;
}
